### PR TITLE
Decrease warning levels

### PR DESCRIPTION
**Pull request by tanaya-bigladder**
Change WARN to INFO for issues that are handled internally and likely to be expected by the user.

### CODE REVIEW

**Review by nealkruis — APPROVED** [review]
This looks fine, but I would really like to clean up the warning level so that it is not a global variable. Can we fit that in here?

We should also confirm what happens for cubic interpolations when there are 2 or 3 grid axis values.

**Comment by tanaya-bigladder** [comment]
> This looks fine, but I would really like to clean up the warning level so that it is not a global variable. Can we fit that in here?
> 
> We should also confirm what happens for cubic interpolations when there are 2 or 3 grid axis values.

Do you mean the 
`extern int LOG_LEVEL`? I was perplexed by that one but assumed it must exist for ease of use.

**Comment by nealkruis** [comment]
Yeah, that's the one. I think we can come up with a better design.

**Comment by tanaya-bigladder** [comment]
As suspected, the cubic interpolation on axes that contain 2 or 3 values just fixes the underspecified point at the same value as the existing endpoint on the relevant side. In other words, if an interpolation happens between index 0 and index 1, the relative coordinates of all the points involved for cubic spline fitting are [-1, 0, 1, 2]. If either points (-1) or (2) are missing, they are fixed to be the same as points (0) or (1) respectively, [here](https://github.com/bigladder/btwxt/blob/af5aa70bcd4ac85ff2666475167a86726589c311/src/griddeddata.cpp#L169). It's currently already [tested](https://github.com/bigladder/btwxt/blob/4f81a435ae59e4d9e6872b3fc3dbc849fbc882d3/test/btwxt_test.cpp#L190) as well, though I haven't re-hand-calculated this to confirm it's right.

**Comment by tanaya-bigladder** [comment]
@nealkruis yes, let's punt. I discovered yesterday that it's a can of worms that will be best with some serious refactoring. I know what we should do but we ought to discuss first.

**Pull request merged**
